version: "3"

services:
  cityHallBE:
    image: openjdk:17-jdk-alpine
    container_name: cityHallBE
    ports:
      - "80:8080"
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - cityHallDB
    networks:
      - cityHallNetwork
    volumes:
      - ./build/libs/CityHallBE-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar

  cityHallDB:
    image: mongo:5.0
    container_name: cityHallDB
    ports:
      - "27017:27017"
    networks:
      - cityHallNetwork

networks:
  cityHallNetwork:
    driver:
      "bridge"